### ISSUE TITLE
Footnotes don't seem to have the correct markup

### ISSUE THREAD

**Issue by jonnay** [dakrone/ox-tufte#4]
It looks like footnotes are emitting a `<p class="footpara">` inside of the  sidenote span.  This breaks sidenote display.  Removing the containing `<p class"footpara">` in the markup fixes it.

Org-mode: 8.3.5
Emacs: 24.5.1
Chrome: 52.0.2743.116

**Comment by dakrone** [comment]
@jonnay hmm.. can you describe how it's breaking? It seems to work correctly for me in both Firefox and Chrome with Org 8.3.5 and Emacs 25.1

**Comment by dakrone** [comment]
I am using ox-tufte to generate https://writequit.org/ and sidenotes display correctly for me, do they display correctly for you as well?

**Comment by jonnay** [comment]
So here is a working example from writequit.org
```
<p>
I am one of the authors of <span class="underline"><a href="http://www.manning.com/hinman">Elasticsearch In Action</a></span> and currently work at
<a href="http://www.elastic.co">Elastic</a> as a core developer<label for="2" class="margin-toggle sidenote-number"></label><input type="checkbox" id="2" class="margin-toggle"/><span class="sidenote">I work on Elasticsearch itself</span>.
</p>
```

Here is my brokenness:

```
<p>
In 2016 I participated in GISHWHES.  One of the items was to make an animation on a Commodore-64.<label for="2" class="margin-toggle sidenote-number"></label><input type="checkbox" id="2" class="margin-toggle"/><span class="sidenote"><p class="footpara">
The Greatest International Scavenger Hunt the World Has Ever Seen.  blahblahblah </p></span>
</p>
```

My guess is that it is something that I am doing inside of my org file that is causing the extra `p` tag to be generated.

Any chance the writequit org source is available somewhere?

**Comment by jonnay** [comment]
http://jonnay.github.io/emagicians-starter-kit/Emagician-Meta.html#orgheadline26 shows the effect. 

https://github.com/jonnay/emagicians-starter-kit/blob/v2/Emagician-Meta.org#inserting-text-chunks is the source.

**Comment by dakrone** [comment]
> http://jonnay.github.io/emagicians-starter-kit/Emagician-Meta.html#orgheadline26 shows the effect. 

Okay, I definitely see that in my browser (firefox) now!

> Emagician-Meta.org#inserting-text-chunks is the source.

Great, I was able to reproduce the issue locally with this org file, I'll try to figure out what's causing this and fix it. Thanks for the reproduction!

**Comment by dakrone** [comment]
@jonnay it seems related to inline versus regular footnotes, I have `org-footnote-define-inline` set to `t` in my config, which is why I wasn't seeing it.

Still working on a fix for it.

**Comment by dakrone** [comment]
@jonnay just pushed a fix for this, thanks for the help reproducing it! Let me know if you have any other problems.

**Comment by jonnay** [comment]
Looks slick, and works like a charm!

Thank you!
