### ISSUE TITLE
Margin Note Images

### ISSUE THREAD

**Issue by jonnay** [dakrone/ox-tufte#6]
Any plans on supporting these?

**Comment by dakrone** [comment]
I just tested locally and I can export with margin images by inserting something that looks like:

```
[[mn:1][this is some file:images/my-pic.jpg text and an image]]
```

Does that work for you as well?

**Comment by dakrone** [comment]
I do think the syntax could be a little nicer, it's certainly a little clumsy currently

**Comment by jonnay** [comment]
Ugh, you're right it does work.  Sorry about the noise.
